### ISSUE TITLE
Unable to Encrypt Inage

### ISSUE THREAD

**Issue by sheshantsinha** [aabhi1/CryptoAlgo#1]
I am unable to encrypt image.
If i wish to encrypt multiple images then how i will do?
Is it necessary to rename all the images to 'file.jpg'?

**Comment by geekygiks** [comment]
Hi.. Sheshant !!

a). What is the error you are getting while encrypting an image. ??
b). It supports encryption of only single image.. for multiple images just run the encryption code multiple number of times.
c). Currently, yes rename the images to file.jpg and run encrypt command. The best way to achieve this is piping the multiple images/renaming them and initiating the encrypt command via shell script.

**Comment by sheshantsinha** [comment]
Interesting thing is this , i am not getting any error but also script is not encrypting image.

**Comment by geekygiks** [comment]
Hi.. Since this is working on my linux box... I think you need to tell more on this.. send the screenshot of what you are getting. Or the image type.. jpg/png/grayscale/rgb.. is text encryption working fine.. ??

**Comment by qimora** [comment]
hi can you teach me how to run this code cause i try to run this code in windows it does not work

**Comment by weldeiyesusayele** [comment]
Hello, everyone, I cant run this project on windows, How can I do?
