### ISSUE TITLE
where did you use this coding

### ISSUE THREAD

**Issue by qimora** [aabhi1/CryptoAlgo#2]
can i know where you use this coding either in linux or window

**Comment by qimora** [comment]
can you teach me to run this code

**Comment by qimora** [comment]
i have try run in windows but it not works

**Comment by geekygiks** [comment]
Hello.. this is coded in linux (debian) and hence will not work in windows env.

**Comment by qimora** [comment]
Ok thanks

**Comment by qimora** [comment]
the coding are you run it in terminal or in the python

**Comment by qimora** [comment]
![capture1](https://user-images.githubusercontent.com/39131422/45469599-bc5ebe00-b75c-11e8-87f1-ee958c859116.JPG)

sir what is the command to encrypt the image file i have try it but it cannot encrypt for image it only encrypt for text only could you please help me

**Comment by qimora** [comment]
and sir can i know where is the source code for this system

**Comment by agabhishek** [comment]
Hi.. write to me at agraj.abhi@gmail.com so that i can tell u in more detail.

**Comment by geekygiks** [comment]
Encrypted images are stored in directory created on the run.
